groups:
  - name: nexus_critical_alerts
    interval: 30s
    rules:
      # Alta taxa de falha em workflows
      - alert: HighWorkflowFailureRate
        expr: |
          rate(temporal_workflow_failed_total[5m]) 
          / 
          rate(temporal_workflow_started_total[5m]) > 0.10
        for: 10m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Taxa de falha de workflows > 10%"
          description: "{{ $value | humanizePercentage }} dos workflows estão falhando"
          
      # Custo de LLM alto
      - alert: HighLLMCostBurn
        expr: rate(llm_total_cost_usd[1h]) * 720 > 100
        for: 30m
        labels:
          severity: warning
          team: finops
        annotations:
          summary: "Custo de LLM projetado > $100/mês"
          description: "Custo atual: ${{ $value | humanize }}/mês"
          
      # Qdrant lento
      - alert: QdrantSlowSearches
        expr: |
          histogram_quantile(0.95, 
            rate(qdrant_search_duration_seconds_bucket[5m])
          ) > 5
        for: 10m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Buscas vetoriais lentas (P95 > 5s)"
          description: "Latência P95 no Qdrant está em {{ $value }}s"
          
      # Temporal down
      - alert: TemporalDown
        expr: up{job="temporal"} == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Temporal Server offline"
          description: "Temporal está inacessível há {{ $value }} minutos"
